---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.4.8
          args:
            - --global.sendanonymoususage=false
            - --global.checknewversion=false
            - --accesslog
            - --log.level=DEBUG
            - --entrypoints.http.Address=:80
            - --entrypoints.https.Address=:443
            - --providers.kubernetescrd
            - --providers.kubernetescrd.namespaces=noteboard
            - --providers.kubernetescrd.allowCrossNamespace=false
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
