---
apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  type: NodePort
  externalTrafficPolicy: "Local"
  ports:
    - protocol: TCP
      name: http
      port: 80
      nodePort: 30080
    - protocol: TCP
      name: https
      port: 443
      nodePort: 30443
  selector:
    app: traefik