---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: noteboard

resources:
- ns.yaml
- ../../base
- ../../base/db
- ../../base/loadbalancer

secretGenerator:
- name: noteboard-frontend-env
  type: Opaque
  files:
  - .env=./data/.env-frontend
- name: noteboard-api-env
  type: Opaque
  files:
  - .env=./data/.env-api
- name: ingress-tls
  files:
  - tls.crt=./data/demo.reliably.local.pem
  - tls.key=./data/demo.reliably.local-key.pem
  type: "kubernetes.io/tls"
  options:
    disableNameSuffixHash: true
