---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-restrictive
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - restrictive
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-permissive
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - permissive
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-permissive
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-permissive
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
