name: Run SLO reports of the Noteboard Frontend service
on:
  push:
    paths:
      - '.github/workflows/frontend-service-ci.yaml'
      - 'apps/noteboard-frontend/**'

env:
  RELIABLY_TOKEN: ${{ secrets.RELIABLY_TOKEN }}

jobs:
  reliably:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code to get the reliably manifest'
        uses: actions/checkout@v2
      - name: 'Setup reliably CLI'
        uses: reliablyhq/gh-action/setup@v1
      - name: 'Is our SLO allowing to deploy?'
        run: |
          echo ${GCP_SA_KEY} >> ./sa.json
          reliably slo report --manifest apps/noteboard-frontend/reliably.yaml -f markdown > report.md
          reliably slo report --manifest apps/noteboard-frontend/reliably.yaml -f json > report.json
          STATUS=$(cat report.json | jq -r '.services[0].service_levels[1].result.slo_is_met')
          echo "Report ended with code: $STATUS"
          if [[ $STATUS == "false" ]]; then
            gh issue create --title "Latency SLO prevents deployment" --body-file report.md
            exit 1
          fi
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ./sa.json
        